### ISSUE TITLE
onFetch is not being fired

### ISSUE THREAD

**Issue by ChristianCRM** [kip-dk/angular-xrmservice#16] opened 2019-10-17 14:35 UTC
Hi Kip,

I am trying to make some basic calculation upon retrieval of records and the onFetch method does not get called by the system.

The documentation only says to create a method named "onFetch" and it will be called automatically.

Thanks

**Comment by ChristianCRM** [comment] 2019-10-17 14:42
Hi Kip,

I am using Dynamics V9 which as minimum uses 8.2 endpoints.

Please look at the code below:

Model class
`export class QuoteDetail extends Entity {
  public crmdqe_ourproductcode: string = null;
  public crmdqe_descriptionfull: string = null;
  public crmdqe_quantity: number = null;
  public crmd_quantityonorder: number = null;
  public crmdqe_salesdiscountedprice: number = null;
  public crmdqe_extendedsalesdiscountedprice: number = null;
  public crmd_classification: OptionSetValue = null;
  public crmdqe_productserviceslookup: EntityReference = new EntityReference().meta('crmdqe_productsserviceses', 'crmdqe_ProductServicesLookup');

  public QuantityRemaining: number;

  constructor() {
    super('crmdqe_quoteproductlines', 'crmdqe_quoteproductlineid', false);
  }

  onFetch(): void {
    console.log('test');
    this.QuantityRemaining = this.crmdqe_quantity - this.crmd_quantityonorder;
  }
}`

then I simply query the system using the xrmContextService.

The only difference is that I use a wrapper around xrmContextService as explained in the documentaiton to create a service for each entity I need to fetch from the database.

**Comment by kip-dk** [comment] 2019-10-17 14:47
hmm. this should work, I assume you do not get "test" in  the console for each row fetched ?

**Comment by kip-dk** [comment] 2019-10-17 14:48
i will create a small unit test on my dev. env. to verify that latest version do not have a breaking change on this, I'll get back to you.

**Comment by kip-dk** [comment] 2019-10-17 14:52
On question, are you fetching the quote details directly, or as a 1:m relation ship on the quote ? (i would like to see the code in the service that calls the xrmcontextservice.query method)

**Comment by ChristianCRM** [comment] 2019-10-17 15:09
The base service uses the xrmContextService, take a look:

`public RetrieveMultiple(condition?: Condition, orderBy?: string, top?: number, count?: boolean): Observable<XrmQueryResult<T>> {
    return this.xrmContextService.query<T>(this.prototype, condition, orderBy, top, count);
  }`

**Comment by ChristianCRM** [comment] 2019-10-17 15:14
As mentioned above. I've tried with the plain xrmContextService.query method and it still doesn't work.

**Comment by kip-dk** [comment] 2019-10-17 15:15
a, ok baseservice is your wrapper on top of the xrmcontextservice. Then i need to see how this.prototype is initialized. It must be initialized with a this.prototype = new SomeEntityModel(...)
you also need to verify that it is never overridden, ex with an object comming from the server through json (such class does not have an onFetch because it was not created with the constructor), finally, if you could do a console.log(this.prototype) just before the call to xrmService.query(..) and verify that the prototype has an onFetch method

**Comment by ChristianCRM** [comment] 2019-10-17 15:19
It is initialized with a new QuoteDetail() call and indeed when I do the console.log for the prototype it does not have the method.

The problem is that the the same thing happens if I do a query(new QuoteDetail(), null) call. The prototype does not have the onFetch method, even though the class has it.

**Comment by kip-dk** [comment] 2019-10-17 15:28
Hmm, what does that mean, the frameworks i assume is still not able to find it ?

**Comment by ChristianCRM** [comment] 2019-10-17 15:31
I don't know why it goes under the proto object and not the QuoteDetail.
In this case that means is not being overridden correctly and the system calls the base onFetch which is empty and does nothing perhaps.

**Comment by kip-dk** [comment] 2019-10-17 15:32
what browser are you using for test

**Comment by ChristianCRM** [comment] 2019-10-17 15:33
Google Chrome 77.0.3865.120

**Comment by kip-dk** [comment] 2019-10-17 15:34
then it is not browser related :-) using same, and the basic functionality works here

**Comment by kip-dk** [comment] 2019-10-17 15:36
can you try, in your service somewhere, simply write console.log(new QuoteDetail())  such call must produce an instance with the onFetch method

**Comment by ChristianCRM** [comment] 2019-10-17 15:37
tried that too and it creates the same thing. I've also added another test method and it also lands into the proto object.

**Comment by ChristianCRM** [comment] 2019-10-17 15:41
This is the tsconfig.json which I haven't touched yet and left as default

`{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}`

When I inspect the onFetch then the body shows the actual implementation that I wrote, so it is indeed coming from the QuoteDetail model.

**Comment by kip-dk** [comment] 2019-10-17 15:48
it's es5, so that not it, and it would be strange if it was even if you was ok with es6 (and less support for older browsers)

**Comment by kip-dk** [comment] 2019-10-17 15:51
the onFetch is always in the prototype section, and here on my objects it works, i will add some additional debugging feature, so we can see how the engine resolve the onFetch on the prototype
apparently it does not find it in your case for some reason. In my end, i am testing on account, competitors, opportunities, contacts and it works everywhere.

**Comment by ChristianCRM** [comment] 2019-10-17 16:10
Tried on version 2.2.11 on another project and it has the same issue.

**Comment by kip-dk** [comment] 2019-10-17 16:16
i am on latest version 2.2.13, i am creating a use case with QuoteDetails to see how it works on my side. It is not that easy to be helpfull when unable to provoke in my environment. The test i am doing i am adding to the git source of the project from where it is released, so it is always latest version.

**Comment by kip-dk** [comment] 2019-10-17 16:21
Looking in the resolve code, and it is very simple:
      if (typeof prototype[prop] === 'function') {
        result[prop] = prototype[prop];
      }

that snipper is running over all properties defined in the prototype, and if it is a function, the function is populated as a proeprty on the result record.

Then when all from prototype > instance has bee done, eventually it will say:

    if (result['onFetch'] !== 'undefined' && result["onFetch"] != null && typeof result["onFetch"] === 'function') {
      result['onFetch']();
    }

**Comment by kip-dk** [comment] 2019-10-17 16:23
could you try do some local tests on your prototype object to see if it fails above tests.

**Comment by kip-dk** [comment] 2019-10-17 18:22
Hi Christian

I am simply not able to create a situation where onFetch is not called as expected. Could i ask you to try the following on your side: 
1) Create a simple service, using the XrmContextService generator, ex for account,that includes the query method, simply copy paste the service into your project, registre it in your module and add the following snipper to the account entity object:

  onFetch(): void {
    console.log('account fetched ' + this.id);
  }

then fetch ex. 2 records with a simple condition (ex isActive()) using only the query method of the generated method.

Please let me know if onFetch is called in this situation.

**Comment by ChristianCRM** [comment] 2019-10-18 08:12
Done.. the test returns true as expected but nothing gets called. Do you prefer doing a remote session and have a look yourself at it?

**Comment by ChristianCRM** [comment] 2019-10-18 08:26
Hi Kipon,

Done the last test and I don't think it can get any simpler than this.

![image](https://user-images.githubusercontent.com/28629328/67078497-50cdf800-f189-11e9-9cb2-405e3cdfe732.png)

It still doesn't show the console.log message

**Comment by kip-dk** [comment] 2019-10-18 08:54
could you print out the number of records fetch 

.subscribe(r => { console.log(r.value.length) })

so we can see that it actually fetch something.

**Comment by ChristianCRM** [comment] 2019-10-18 08:56
It has. I've looked at the network tab and I can see there is an account fetched.
Maybe it would be better if we connect remotely and you take a look at it rather than keep posting here.

**Comment by ChristianCRM** [comment] 2019-10-18 08:57
I've also tried to call the onFetch function on the results manually and it gives me the error saying that onFetch is not a function.

**Comment by kip-dk** [comment] 2019-10-18 08:57
that can work for me, but i am at a customer now not sure what timezone you are in, but around 16.00 DK time  (that is currently UTC+2)

**Comment by ChristianCRM** [comment] 2019-10-18 08:59
Alright, I'll setup a meeting request for that time

**Comment by kip-dk** [comment] 2019-10-18 09:38
I got the invitation, but could you try below case that i have just verified in my end:

A service like this:

import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { XrmQueryResult, XrmContextService, Entity, Entities, EntityReference, OptionSetValue, Condition, Operator, Comparator } from 'kipon-xrmservice';

export class Account extends Entity {
  constructor() {
    super('accounts', 'accountid', false);
  }
  accountnumber: string = null;

  meta(): Account {
    return this;
  }
  onFetch(): void {
    console.log('hello from account service for account:' + this.id);
  }
}

@Injectable()
export class AccountService {
  private localPrototype: Account = new Account().meta();
  constructor(private xrmService: XrmContextService) { }

  query(): Observable<XrmQueryResult<Account>> {
    let condition: Condition = new Condition().isActive();
    return this.xrmService.query<Account>(this.localPrototype, condition);
  }
}


In your app.module:

import { AccountService } from './services/account.service';

.....

  providers: [
    AccountService,
  ],



In your component.ts:

  callAccountService(): void {
    this.accountService.query().subscribe(r => {
      console.log(r);
    });
  }


In your component.html

  <button (click)="callAccountService()">account service test</button>


Output from clicking the button in my environment:

hello from account service for account:c54bec0b-b543-e711-a962-000d3a27d441
account.service.ts:15 
hello from account service for account:28e45114-b543-e711-a962-000d3a27d441
account.service.ts:15 
hello from account service for account:eb52de1a-b543-e711-a962-000d3a27d441
account.service.ts:15 
hello from account service for account:cb5aa321-b543-e711-a962-000d3a27d441
account.service.ts:15 
hello from account service for account:d3e5e064-8c1d-e811-a980-000d3a27d441
account.service.ts:15 
hello from account service for account:f05f570c-ea28-e811-a980-000d3a27d441
account.service.ts:15 
hello from account service for account:db396317-ea28-e811-a980-000d3a27d441
ctx.component.ts:546 
{context: "http://kipon-dev/kip/api/data/v8.2/$metadata#accounts(accountid,accountnumber)", count: undefined, value: Array(7), pages: Array(1), pageIndex: 0, …}

**Comment by ChristianCRM** [comment] 2019-10-18 10:25
Hi Kip,

I've created a brand new Angular app and copy-pasted the code above and still don't see any call from the onFetch method. The account is retrieved successfully but nothing else happens.

What angular version are you using? I'm on version 8

**Comment by kip-dk** [comment] 2019-10-18 10:29
still using 7, but let me create app in version 8 to see if i an provoke there. Maeby that is the root cause

**Comment by kip-dk** [comment] 2019-10-18 10:31
hmmm.  angular 8 is doing even more optimization than angular 7 (removing things that are "not used") i think it is removing the onFetch method because it is never references anywhere, i will look into that track

**Comment by ChristianCRM** [comment] 2019-10-18 10:36
That sounds like a possible explanation. In fact, if I try to call the onFetch method on the returned items the console gives an error sayin that onFetch is not a function.

**Comment by kip-dk** [comment] 2019-10-18 10:38
for a temporary solution, try make a reference to the onFetch in you service,  ex
private localPrototype = new Account().meta();
this.onFetchDummy = this.localPrototype.onFetch

**Comment by kip-dk** [comment] 2019-10-18 11:53
Hi Christian, I am able to provoke the problem on angular 8, so we do not need a session this afternoon. I will try find a workaround, and also provided needed changes in the concept to support this without "workarounds". The later might cause minor changes to the onFetch "api", but that is how it is when technologies evolve. I will keep you updated.  Thanks for pointing this issue out. Sooner or later i would have been hit by a buss, -- when upgrading one of my many projects to angular 8.

**Comment by kip-dk** [comment] 2019-10-18 12:34
now i think i understand the root cause. Angular 8 is "smart", it is running ES6 if the browser supports is and ES5 if is does not. In ES6,  for (var prop in object)  will not return methods, only properties, so the framework does not find the onFetch, even though it is there. The good news is, that it is easy to fix, without changes to the api, i just need to learn the framework, to also look for methods in the prototype. I will try release a new version later, when i have a fix, and performed some test. The root problem is not only related to onFetch(), but to any method you add to the prototype. For angular 8, they will not be populated as expected on objects returned, and it will produce strange "function not found" script errors when upgrading existing solutions to angular 8

**Comment by kip-dk** [comment] 2019-10-18 13:01
Hi Christian, I am happy to tell you, that version 2.2.14 is fixing above problems (both for onFetch and other prototype methods on the entity), and the functionality now also works with ES6. I am closing the issue. Thanks for staying tuned, and keep me on the track on solving this issue.

**Closed by kip-dk** 2019-10-18 13:01 UTC
