### ISSUE TITLE
Nested Applications

### ISSUE THREAD

**Issue by ChristianCRM** [kip-dk/angular-xrmservice#13] opened 2019-08-30 08:38 UTC
Hello Kip,

I have developed two separate applications using this xrm service package. One of the client has requested to have both apps work one within the other.
So I have the first app running in a webreource which pops out in a new window and the second app running in an iframe within it.
This works perfectly in development, but when I switch to production the second app still tries to call localhost endpoints instead of the actual crm server.
I'm not sure if this is an issue or I am doing (or not doing) something to make it work.

Thanks

Christian

**Comment by kip-dk** [comment] 2019-08-30 09:09
The reason is that the iframe in the popup tries to find the context in the outer form, and that does not expose it.

In developer mode you get a fake context in both places, and therefore it works.

A simple solution would be to let the ctx resolver in xrm service, expose the context through so any iframe in the page would find it there.

I will take a look at that idea and get back to you sometime later today.

if you need a solution now, you will need to do some code in the iframe that is loaded before the angular app, and set wndows["GetGlobalContext"] and that method will need to return the context.

But as said, it should not be that hard for the framework to support this scenario, so i will take a look at that.

**Comment by ChristianCRM** [comment] 2019-08-30 10:30
Thank you for the reply,
Are you able to implement it in the next 2 or 3 days? Otherwise could you supply some sample code on how to do it in the mean time please?

**Comment by kip-dk** [comment] 2019-08-30 10:40
I will release a version later today, i will keep you updated. Getting the conext is very centralized in the service, so it is very easy to accomplish what we need here. I just don't have any usecase that uses nested iframes, so i am create a simple one of these as well to test that it is working.

**Comment by kip-dk** [comment] 2019-08-31 07:53
I Christian a new version 2.2.9 has been released to npm. I do not have a lot of test cases with deep iframing, because i preffer to build single angular apps. with multi components, and they are easy to layout on same page. I will appreciate if you will give some feedback on the test, and then i will close the case if it works. If it should not work, please rollback to version 2.2.8, and tell me about the problem, and i will try fix asap.

If you take a look at [https://github.com/kip-dk/angular-xrm-webresource](url) it explains how you can have a single angular app with several dynamics 365 entry points using angular routes. If you had use such approach you might not have needed the iframes at all.

Happy dynamics 365, angular coding, at let me know when you have tested the deep context sharing.

**Comment by ChristianCRM** [comment] 2019-09-02 08:25
Hi Kip,

I have updated the package and rebuilt the app which no longer works now and I get this error in production mode

[cid:image001.png@01D56170.66321F90]

Regards,

Christian Dornetto

**Comment by kip-dk** [comment] 2019-09-02 08:27
hi christian, i cannot see the image for some reason.

**Comment by kip-dk** [comment] 2019-09-02 08:29
For now, please role back to version 2.2.8, when I see what error you receive i will try to solve ASAP.

until then, you can try do the following in your outer form, as a script directly on the index.html

<script type='javascript'>
if (window.opener && window.opener.Xrm && !window.Xrm) {
   window.Crm = window.opener.Xrm;
} 
</script>

**Comment by ChristianCRM** [comment] 2019-09-02 08:32
Hi Kip,

I've just replied to the email and did not realise it doesn't upload the image correctly.

![image](https://user-images.githubusercontent.com/28629328/64100931-99aa2880-cd64-11e9-8822-c47b841deac1.png)

Here's the screenshot of the error.

**Comment by kip-dk** [comment] 2019-09-02 08:40
hmmm. apparent the real "Xrm" does not like to be shared cross iframes  the fix above will problerbly give same result :-(

**Comment by ChristianCRM** [comment] 2019-09-02 08:47
Can it be fixed? Is there an alternative approach to it?

**Comment by kip-dk** [comment] 2019-09-02 08:53
Could you try take version 2.2.10, and see if a quick fix works. I will not be able to do prober test until this evening, and my current tests are running in a "fake" setup, that is why i do not see the errors. I will need to deploy to a real dynamics 365 installation, to see the interoperability with the real Xrm and the real "GetGlobalContext", but now it no longer tries to short-cut these objects by copy them to local references, and that quick fix might be enough to get it to work.

**Comment by ChristianCRM** [comment] 2019-09-02 09:21
Still getting the same error...

**Comment by kip-dk** [comment] 2019-09-02 09:25
hmm. that is strange, I will test later today by deploying my example to a real installation. 

Please go back to version until then 2.2.8. 

For now i do not have a good workaround, because the workaround i suggestion is actually what the code is doing, and apparently the Dynamics version of  "Xrm" does not like that.

But I am pretty sure it can be solved.

**Comment by ChristianCRM** [comment] 2019-09-02 09:49
Ok, please let me know asap today as I have to give a demo tomorrow and I need a fix in place by then.

**Comment by kip-dk** [comment] 2019-09-02 09:57
i have identified the problem, now i need to figure out the solution 
the problem is
this does not work:
var x = window.parent.opener.Xrm.Page.ui.getFormType;
if (x() == 2) do something

this does work
if (window.parent.opener.Xrm.Page.ui.getFormType() == 2) do something

The difference is proberbly that the "this" context is changed when added to a local variable.
The challange is that i wish to bee 100% generic in the way i find things, and that is very hard without saving the findings along-the-way, but now i know what the problem is about, that should make it easier to fix.

**Comment by kip-dk** [comment] 2019-09-03 06:50
It turned out to be dueable, but not as trivial as I hoped for.  Version 2.2.11 now support nested iframes, and it has been tested within i Dynamics 365 Webresources context.  Pleasee read the changelog on git, or on the projects npmjs site. I will appreciate your feecback, so i can close the issue.

**Comment by kip-dk** [comment] 2019-09-04 09:34
Hi Christian. Did you deliver on your demo, and did you manage to verify the iframe concept in version 2.2.11.

**Comment by ChristianCRM** [comment] 2019-09-06 09:59
Hi Kip,

Sorry for the late reply.

Yes your fix seems to work very well and the two application cohexist within the same window. The demo was delivered and the outcome was positive. This has gone into staging and I will keep you posted if anything comes up before we release it.

Regards,

Christian

**Comment by kip-dk** [comment] 2019-09-06 10:50
Tnx. for your reply, and good to hear you had a successfull demo. I apreciate your support for the project. - closing the issue.

**Closed by kip-dk** 2019-09-06 10:50 UTC

**Comment by christiandornetto** [comment] 2020-09-11 10:58
Hello Kip,

I've been trying to perform some update on one of the nested application and it now throws a different error when trying to query entities using the xrmContextService. See below:

![image](https://user-images.githubusercontent.com/38754730/92917097-0ea74800-f426-11ea-8267-706b3df3d0f6.png)

Any idea on how to solve this?

**Comment by kip-dk** [comment] 2020-09-11 11:04
hi Christian   i looks like the "e" for whatever reason do not have getClientUrl(), so depending how you bootstrap you angular app, that might be cause by different things.  What version of kipon-xrmservice are you using, and does this show up in developer mode (ng server) or when running inside dynamics 365 as web resource, and finally can you share your index.html file so i can see if you are loading GlobalContext from dynamics 365. That might also cause problems because getClientUrl are no longer available in newer online dynamics 365 installations

**Comment by christiandornetto** [comment] 2020-09-11 11:59
Hi Kip,
Thanks for the quick response. This doesn't happen when the application runs standalone (on a record form for example) but it does when it runs in an iframe of another angular application.

The index file is as below and indeed it doesn't contain the global context file as it is deprecated.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>SurveyApp</title>
    <base href="" />

    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/x-icon" href="favicon.ico" />
  </head>
  <body>
    <crmd-root></crmd-root>
  </body>
</html>
```

**Comment by kip-dk** [comment] 2020-09-11 12:05
so  we have an entity form ... inside that an iframe.webresource and inside that and iframe.webresouce  ...    what version of CRM, and classic or unified interface (just so i can create the correct scenario on my dev environemt). i never create iframes in iframes, so there might be a new problem in that situation.

**Comment by christiandornetto** [comment] 2020-09-11 12:11
The application runs by clicking on a ribbon button which pops up a webresource (I assume this is the first frame). Then within this application there is another Iframe that embeds the second application. This used to work until I discovered today that it no longer does.

Using Dynamics version 9.1 with UCI

**Comment by kip-dk** [comment] 2020-09-11 12:14
thanks,  popup and iframe is not 100% the same,  we are getting the context from  opener  in the first case and parent in the second,  i will create that scenario on my test box.

**Comment by kip-dk** [comment] 2020-09-11 12:15
one more question,  does the first popup have the xrmcontext service, i assume so, otherwise i know for sure it will not work.

**Comment by christiandornetto** [comment] 2020-09-11 12:26
yes both of them have as the second app can work independently as well
